# Generated by Django 6.0.6 on 2026-07-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, help_text='Clase Bootstrap Icon (ej: bi-shield-lock)', max_length=50, verbose_name='Icono')),
                ('url_name', models.CharField(blank=True, help_text='Nombre de ruta Django (ej: security:user_list)', max_length=200, verbose_name='URL interna')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, help_text='Null = módulo raíz en el sidebar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Módulo padre')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Visible solo para usuarios con estos permisos. Vacío = visible para todos.', to='auth.permission', verbose_name='Permisos requeridos')),
            ],
            options={
                'verbose_name': 'Elemento de menú',
                'verbose_name_plural': 'Elementos del menú',
                'ordering': ['order', 'name'],
            },
        ),
    ]
